# Generated by Django 4.2.1 on 2023-07-06 23:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_step_upvotes_step_user_alter_step_pub_date_upvote'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=0, verbose_name='Level of the user')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='step',
            name='upvotes',
            field=models.ManyToManyField(related_name='upvoted_steps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Upvote',
        ),
    ]
