# Generated by Django 4.2.1 on 2023-07-07 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofile_alter_step_upvotes_delete_upvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='unit_number',
            field=models.FloatField(default=0, verbose_name='Unit Number'),
        ),
    ]
