# Generated by Django 4.2.1 on 2023-07-07 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userprofile_unit_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='unit_number',
            field=models.FloatField(default=0, verbose_name='Unit Number'),
        ),
    ]
