# Generated by Django 4.2.1 on 2023-07-07 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_step_unit_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='level',
        ),
    ]
