# Generated by Django 4.2.1 on 2023-07-07 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_step_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='unit_number',
            new_name='total_unit_number',
        ),
    ]
